spring:
  application:
    name: realtime-ingestion-service

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: ai-intelligence-group
      auto-offset-reset: earliest

      key-deserializer:
        org.apache.kafka.common.serialization.StringDeserializer

      value-deserializer:
        org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: com.aicloudsec.streaming.model

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info

cloud:
  aws:
    kinesis:
      stream-name: security-telemetry-stream

ai:
  service:
    url: http://localhost:8083
